feat: check PACKAGE_NAME before running

diff --git a/.github/workflows/build.yml b/.github/workflows/build.yml
--- a/.github/workflows/build.yml
+++ b/.github/workflows/build.yml
@@ -8,6 +8,12 @@ jobs:
     steps:
       - uses: actions/checkout@v3
 
+      - name: Check for PACKAGE_NAME variable exists
+        if: ${{ vars.PACKAGE_NAME == '' }}
+        run: |
+          echo "error: PACKAGE_NAME is not declared in reposirory's variables."
+          exit 1
+
       - name: Build the package builder docker image
         working-directory: builder
         run: docker build . --tag builder:latest
diff --git a/.github/workflows/check-update.yml b/.github/workflows/check-update.yml
--- a/.github/workflows/check-update.yml
+++ b/.github/workflows/check-update.yml
@@ -23,6 +23,12 @@ jobs:
     steps:
       - uses: actions/checkout@v3.1.0
 
+      - name: Check for PACKAGE_NAME variable exists
+        if: ${{ vars.PACKAGE_NAME == '' }}
+        run: |
+          echo "error: PACKAGE_NAME is not declared in reposirory's variables."
+          exit 1
+
       - name: Config git for commit
         run: |
           git config user.name "Check update workflow[bot]"
